# Generated by Django 5.2.8 on 2025-12-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner_app', '0002_user_shortenedurl_user_alter_shortenedurl_short_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
