# Generated by Django 5.2.8 on 2025-12-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner_app', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
